### ISSUE TITLE
iIcon error when launching a server

### ISSUE THREAD

**Issue by iwo-strzebonski** [iwo-strzebonski/ThaumicRevelations#1]
**Describe the bug**
Exception in server tick loop

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Caused by: java.lang.NoSuchFieldError: iIcon
	at trevelations.block.BlockExcubitura.<init>(BlockExcubitura.java:20)
	at trevelations.common.ThaumRevContent.loadBlocks(ThaumRevContent.java:30)
	at trevelations.common.ThaumicRevelations.preInit(ThaumicRevelations.java:39)

**Comment by iwo-strzebonski** [comment]
Repaired, closing
